makeCosinorArray=function(tt,Nsamp,freqs,acros,Amp=1,sigma=1){
  # generate an array corresponding to Amp*cos(2*pi*tt*freqs-acro)+rnorm(Nsamp),
  # the array will be of size length(tt) x Nsamp x Nacro x Nfreq.
  # NOTE: noise samples are generated independently for each acro/freq/timepoint
  #
  # NOTE: if after constructing the cosinor array, if you want to unpack a scalar
  # function the array in a way that is compatible with the indexing of a
  # dataframe generated by expand.grid(acros,freqs), make sure that you unpack
  # as a vector
  #      res |> as.vector()
  # see fastMCTinfpower() for an actual example of this kind of unpacking

  lt = length(tt)
  lf = length(freqs)
  la = length(acros)
  dims = c(lt,Nsamp,lf,la)

  tt_arr = array(tt, dim = c(lt,1,1,1)) |> array(c(lt,Nsamp,lf,la))
  f_arr  = array(rep(freqs, each=lt*Nsamp,times=la),  dim = c(lt, Nsamp, lf, la))
  a_arr  = array(rep(acros, each = lt*Nsamp*lf), dim = c(lt, Nsamp, lf, la))

  c_arr = Amp*cos(2*pi*tt_arr*f_arr-a_arr)
  noise = array(rnorm(Nsamp*lt*la*lf),c(lt,Nsamp,lf,la))
  c_arr = c_arr + sigma*noise
  return(c_arr)
}
